name: auto_benchmark
on:  
  pull_request:    
    branches:
    - main  
  push:
    branches:
    - main
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Build and test with Docker
        run: |
            docker build --tag openmc_docker .
            docker run -v $PWD:/share openmc_docker 
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

#docker run --rm openmc_docker python run_all_simulations.py